name: stockify
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  get: ^4.6.6
  firebase_auth: ^4.19.5
  image_picker: ^1.1.1
  qr_flutter: ^4.0.0
  firebase_storage: ^11.7.0
  path_provider: ^2.1.2
  #flutter_image_compress: ^2.3.0
  barcode_widget: ^2.0.0
  pretty_qr_code: ^3.3.0
  shimmer: ^3.0.0
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0





  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  rxdart: ^0.27.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  qr_code_scanner: ^1.0.1
  audioplayers: ^6.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  image: ^4.1.7
  firebase_messaging: ^14.8.2
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.1
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  ionicons: ^0.2.2
  fl_chart: ^0.68.0
  syncfusion_flutter_pdf: ^25.2.4
  printing: ^5.12.0
  scrollable_positioned_list: ^0.3.8
  barcode_scan2: ^4.3.0
  syncfusion_flutter_charts: ^25.2.4
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/iconapp.png"



dev_dependencies:
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.2.1
  flutter_login_facebook: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/avatar.png
    - assets/image/
    - assets/audio/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: nsb
      fonts:
        - asset: res/font/Noto_Sans_Buhid.ttf

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #