// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0aevTV1foa9Xb02KRvWpOQAlDYFndEw',
    appId: '1:14741847490:web:5b2f29bb8f85959e12ea5b',
    messagingSenderId: '14741847490',
    projectId: 'stockifyproject',
    authDomain: 'stockifyproject.firebaseapp.com',
    storageBucket: 'stockifyproject.appspot.com',
    measurementId: 'G-88HK361LD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJiasFbK9gR_rBphwmy1XPpXDHrJFEnY',
    appId: '1:14741847490:android:c715816751bf268612ea5b',
    messagingSenderId: '14741847490',
    projectId: 'stockifyproject',
    storageBucket: 'stockifyproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAed9zaWOXJO-p8vsF31nbQdhOqjdbHh94',
    appId: '1:14741847490:ios:440c4e0bd977765612ea5b',
    messagingSenderId: '14741847490',
    projectId: 'stockifyproject',
    storageBucket: 'stockifyproject.appspot.com',
    iosClientId: '14741847490-eo7cdm5hurp229jqj5d03knmll4gavne.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAed9zaWOXJO-p8vsF31nbQdhOqjdbHh94',
    appId: '1:14741847490:ios:440c4e0bd977765612ea5b',
    messagingSenderId: '14741847490',
    projectId: 'stockifyproject',
    storageBucket: 'stockifyproject.appspot.com',
    iosClientId: '14741847490-eo7cdm5hurp229jqj5d03knmll4gavne.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0aevTV1foa9Xb02KRvWpOQAlDYFndEw',
    appId: '1:14741847490:web:18c9000f0653cdc112ea5b',
    messagingSenderId: '14741847490',
    projectId: 'stockifyproject',
    authDomain: 'stockifyproject.firebaseapp.com',
    storageBucket: 'stockifyproject.appspot.com',
    measurementId: 'G-9K0T0VB1NM',
  );

}